var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/reclassify/route.js")
R.c("server/chunks/app_api_reclassify_route_ts_0tp7u~1._.js")
R.c("server/chunks/node_modules_next_0vppqbq._.js")
R.c("server/chunks/node_modules_@supabase_postgrest-js_dist_index_mjs_0uel2xe._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00jw3pg._.js")
R.c("server/chunks/node_modules_openai_07ydydx._.js")
R.c("server/chunks/node_modules_0d0l_0n._.js")
R.c("server/chunks/[root-of-the-server]__06on6ov._.js")
R.c("server/chunks/_next-internal_server_app_api_reclassify_route_actions_0skkpuu.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/reclassify/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/reclassify/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
